// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB55-pH5pW3qEBP4Y79psiZap7Y0JXR6Kc',
    appId: '1:265550677472:web:77632e3e89e54dacac5785',
    messagingSenderId: '265550677472',
    projectId: 'meine-app-2f3fd',
    authDomain: 'meine-app-2f3fd.firebaseapp.com',
    storageBucket: 'meine-app-2f3fd.firebasestorage.app',
    measurementId: 'G-SXYDBBL2NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCauBVlax__Di3Uq_zao81m57zAX958TYw',
    appId: '1:265550677472:android:ac42790740cc1201ac5785',
    messagingSenderId: '265550677472',
    projectId: 'meine-app-2f3fd',
    storageBucket: 'meine-app-2f3fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ykbowck_kamjqpxHevEHUS4gsEaSaW0',
    appId: '1:265550677472:ios:b34dfa6d7aa3293fac5785',
    messagingSenderId: '265550677472',
    projectId: 'meine-app-2f3fd',
    storageBucket: 'meine-app-2f3fd.firebasestorage.app',
    iosBundleId: 'com.example.meineApp',
  );

}